[package]
name = "qdrant-client"
version = "0.11.5"
edition = "2021"
authors = ["Qdrant Team <team@qdrant.com>"]
description = "Rust client for Qdrant Vector Search Engine"
documentation = "https://docs.rs/qdrant-client"
homepage = "https://qdrant.tech/"
license = "Apache-2.0"
repository = "https://github.com/qdrant/rust-client"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.8.3", features = ["tls", "tls-roots"] }
prost = "0.11.5"
prost-types = "0.11.5"
anyhow = "1"
reqwest = { version = "0.11.13", optional = true, features = ["stream"] }
futures-util = { version = "0.3.25", optional = true }

[build-dependencies]
tonic-build = { version = "0.8.4", features = ["prost"] }

[dev-dependencies]
tokio = "1.23.0"

[features]
default = ["download_snapshots"]
download_snapshots = ["reqwest", "futures-util"]
