[package]
name = "qdrant-client"
version = "0.8.4"
edition = "2021"
authors = ["Qdrant Team <team@qdrant.com>"]
description = "Rust client for Qdrant Vector Search Engine"
documentation = "https://docs.rs/qdrant-client"
homepage = "https://qdrant.tech/"
license = "Apache-2.0"
repository = "https://github.com/qdrant/rust-client"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.7.2"
prost = "0.10.1"
prost-types = "0.10.1"

[build-dependencies]
tonic-build = { version = "0.7.2", features = ["prost"] }


[dev-dependencies]
tokio = "1.19.2"
