[package]
name = "qdrant-client"
version = "0.9.0"
edition = "2021"
authors = ["Qdrant Team <team@qdrant.com>"]
description = "Rust client for Qdrant Vector Search Engine"
documentation = "https://docs.rs/qdrant-client"
homepage = "https://qdrant.tech/"
license = "Apache-2.0"
repository = "https://github.com/qdrant/rust-client"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.8.0"
prost = "0.11.0"
prost-types = "0.11.1"
anyhow = "1"
reqwest = { version = "0.11.11", optional = true }

[build-dependencies]
tonic-build = { version = "0.8.0", features = ["prost"] }

[dev-dependencies]
tokio = "1.20.1"

[features]
default = ["download_snapshots"]
download_snapshots = ["reqwest"]
