[package]
name = "qdrant-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.7.2"
prost = "0.10.1"
prost-types = "0.10.1"

[build-dependencies]
tonic-build = { version = "0.7.2", features = ["prost"] }


[dev-dependencies]
tokio = "1.19.2"