[package]
name = "qdrant-client"
version = "1.1.2"
edition = "2021"
authors = ["Qdrant Team <team@qdrant.com>"]
description = "Rust client for Qdrant Vector Search Engine"
documentation = "https://docs.rs/qdrant-client"
homepage = "https://qdrant.tech/"
license = "Apache-2.0"
repository = "https://github.com/qdrant/rust-client"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.9.2", features = ["tls", "tls-roots"] }
prost = "0.11.9"
prost-types = "0.11.9"
anyhow = "1"

# If you don't want to have serde as a dependency, please consider contributing a feature flag
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11.18", optional = true, default-features = false, features = ["stream", "rustls-tls"] }
futures-util = { version = "0.3.28", optional = true }

[dev-dependencies]
tonic-build = { version = "0.9.2", features = ["prost"] }
tokio = { version = "1.28.1", features = ["rt-multi-thread"] }

[features]
default = ["download_snapshots"]
download_snapshots = ["reqwest", "futures-util"]
